get http://localhost:3003/alluser


###

post http://localhost:3003/user
Content-Type: application/json

{
    "name": "Luiz",
	"nickname": "luizbm",
	"email": "luizbm@dev.com"
}


###

get http://localhost:3003/user/162718609160