get http://localhost:3003/alluser


###

post http://localhost:3003/user
Content-Type: application/json

{
    "name": "Luiz",
	"nickname": "luizbm",
	"email": "luizbm@dev.com"
}


###

get http://localhost:3003/user/1627175632470


###

put http://localhost:3003/user/edit/1627175632470
Content-Type: application/json

{
    "name": "Usuário teste",
    "nickname": "nickTeste",
    "email": "email_Teste@dev.com"
}

###

post http://localhost:3003/task
Content-Type: application/json

{
    "title": "tarefa teste",
    "description": "testando as validações",
	"limit_date": "29/07/2021",
	"creator_user_id": "1627173068135"   
}
