post http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Eliane",
    "email": "ee@email.com",
    "password": "123456"
}

###
get http://localhost:3003/user/pi@email.com


###
post http://localhost:3003/login
Content-Type: application/json

{
    "email": "ee@email.com",
    "password": "123456"
}