//Endpoint 1
post http://localhost:3003/user
Content-Type: application/json

{
    "name": "Charles grey",
    "email": "rey@gmail.com",
	"age": 37
}

###

post http://localhost:3003/product
Content-Type: application/json

{
    "name": "Fones",
    "description": "Fones de ouvido JBL TUNE 500BT coloridos",
	"price": 256
}


###

get http://localhost:3003/allUser


###

get http://localhost:3003/allProduct




