//Endpoint 1
post http://localhost:3003/user
Content-Type: application/json

{
    "name": "Micheline Barros",
    "email": "mms@gmail.com",
	"age": 35
}

###

post http://localhost:3003/product
Content-Type: application/json

{
    "name": "Fones",
    "description": "Fones de ouvido JBL TUNE 500BT coloridos",
	"price": 256
}


###

get http://localhost:3003/allUser



